# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logproto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

import es2loki.proto.gogo_pb2 as gogo__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0elogproto.proto\x12\x08logproto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ngogo.proto"N\n\x0bPushRequest\x12?\n\x07streams\x18\x01 \x03(\x0b\x32\x17.logproto.StreamAdapterB\x15\xea\xde\x1f\x07streams\xda\xde\x1f\x06Stream"e\n\rStreamAdapter\x12\x1a\n\x06labels\x18\x01 \x01(\tB\n\xea\xde\x1f\x06labels\x12\x38\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x16.logproto.EntryAdapterB\x0f\xc8\xde\x1f\x00\xea\xde\x1f\x07\x65ntries"e\n\x0c\x45ntryAdapter\x12=\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0e\x90\xdf\x1f\x01\xc8\xde\x1f\x00\xea\xde\x1f\x02ts\x12\x16\n\x04line\x18\x02 \x01(\tB\x08\xea\xde\x1f\x04lineB&Z$github.com/grafana/loki/pkg/logprotob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "logproto_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z$github.com/grafana/loki/pkg/logproto"
    _PUSHREQUEST.fields_by_name["streams"]._options = None
    _PUSHREQUEST.fields_by_name[
        "streams"
    ]._serialized_options = b"\352\336\037\007streams\332\336\037\006Stream"
    _STREAMADAPTER.fields_by_name["labels"]._options = None
    _STREAMADAPTER.fields_by_name[
        "labels"
    ]._serialized_options = b"\352\336\037\006labels"
    _STREAMADAPTER.fields_by_name["entries"]._options = None
    _STREAMADAPTER.fields_by_name[
        "entries"
    ]._serialized_options = b"\310\336\037\000\352\336\037\007entries"
    _ENTRYADAPTER.fields_by_name["timestamp"]._options = None
    _ENTRYADAPTER.fields_by_name[
        "timestamp"
    ]._serialized_options = b"\220\337\037\001\310\336\037\000\352\336\037\002ts"
    _ENTRYADAPTER.fields_by_name["line"]._options = None
    _ENTRYADAPTER.fields_by_name["line"]._serialized_options = b"\352\336\037\004line"
    _PUSHREQUEST._serialized_start = 73
    _PUSHREQUEST._serialized_end = 151
    _STREAMADAPTER._serialized_start = 153
    _STREAMADAPTER._serialized_end = 254
    _ENTRYADAPTER._serialized_start = 256
    _ENTRYADAPTER._serialized_end = 357
# @@protoc_insertion_point(module_scope)
